version: '3.7'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src:/discord-bot/app/src
    container_name: discord-bot
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run start:prod
